### ISSUE TITLE
TODOs before v0.1

### ISSUE THREAD

**Issue by GiggleLiu** [XingyuZhang2018/VUMPS.jl#8]
* [x] using the `joinpath` function rather than direct concatenation of strings.
* [x] using [`PkgTemplates`](https://github.com/invenia/PkgTemplates.jl) to setup CI, documentation and include their badges in the README. Remove `.travis.yml` because it is not free now.
* [x] Include doctests in the tests.

**Comment by GiggleLiu** [comment]
Question:
```julia
    @inbounds @views for j in 1:Nj, i in 1:Ni
        AC[:,:,:,i,j] = ein"asc,cb -> asb"(AL[:,:,:,i,j], C[:,:,i,j]) 
    end
```

Is it faster than
```julia
AC = ein"ascij,cbij -> asbij"(AL, C) 
```
?

**Comment by XingyuZhang2018** [comment]
Oh, thanks! I did not think this simple efficient way which is faster than before. I should rewrite all maps in this way.
